import { Component } from '@angular/core';
import { Influencer } from 'src/types/influencer';
@Component({
    selector: 'app-exclusive',
    templateUrl: './exclusive.component.html',
})
export class ExclusiveComponent {
    detailsCard: Influencer[] = [
        {
            name: 'menostrece',
            img: '../../../assets/exclusives/menos-trece.jpg',
            instagram: 'https://www.instagram.com/menos_trece/',
            twitch: 'https://www.twitch.tv/menostrece',
            twitter: 'https://twitter.com/menos_trece',
            youtube: 'https://www.youtube.com/user/MenosTreceYT',
        },
        {
            name: 'knekro',
            img: '../../../assets/exclusives/knekro.jpg',
            instagram: 'https://www.instagram.com/knekro_/',
            twitch: 'https://www.twitch.tv/knekro',
            twitter: 'https://twitter.com/KNekro',
            youtube: 'https://www.youtube.com/user/KNekroGamer',
        },
        {
            name: 'revenant',
            img: '../../../assets/exclusives/revenant.jpg',
            instagram: 'https://www.instagram.com/luismi_revenant/',
            twitch: 'https://www.twitch.tv/revenant',
            twitter: 'https://twitter.com/G4G_Revenant',
            youtube: 'https://www.youtube.com/user/RevenantL0L',
            youtubeSecondary: 'https://www.youtube.com/user/Gaming4GamersTV',
        },
        {
            name: 'pikahimovic',
            img: '../../../assets/exclusives/pikahimovic.jpg',
            instagram: 'https://www.instagram.com/knekro_/',
            twitch: 'https://www.twitch.tv/knekro',
            twitter: 'https://twitter.com/KNekro',
            youtube: 'https://www.youtube.com/user/KNekroGamer',
        },
        {
            name: 'makina',
            img: '../../../assets/exclusives/makina.jpg',
            instagram: 'https://www.instagram.com/makina_yt/',
            twitch: 'https://www.twitch.tv/makina',
            twitter: 'https://twitter.com/MakinaYT',
            youtube: 'https://www.youtube.com/user/30secondsforkill',
        },
        {
            name: 'mayorcete',
            img: '../../../assets/exclusives/mayorcete.jpg',
            instagram: 'https://www.instagram.com/mayorcete/',
            twitch: 'https://www.twitch.tv/mayorcete',
            twitter: 'https://twitter.com/MayorceteGaming',
            youtube: 'https://www.youtube.com/user/MayorceteGamingTV',
        },
        {
            name: 'winghaven',
            img: '../../../assets/exclusives/winghaven.png',
            instagram: 'https://www.instagram.com/winghaven/',
            twitch: 'https://www.twitch.tv/winghaven',
            twitter: 'https://twitter.com/Winghahaven',
            youtube: 'https://www.youtube.com/channel/UCAwfg2i_sTwqrYmh8UBGGjA',
        },
        {
            name: 'hugothester',
            img: '../../../assets/exclusives/hugothester.jpg',
            instagram: 'https://www.instagram.com/hugothester/',
            twitch: 'https://www.twitch.tv/hugothester',
            twitter: 'https://twitter.com/hugothester',
            youtube: 'https://www.youtube.com/user/hugothester',
        },
        {
            name: 'katth',
            img: '../../../assets/exclusives/Katth.jpg',
            instagram: 'https://www.instagram.com/katthtv/',
            twitch: 'https://www.twitch.tv/katth',
            twitter: 'https://twitter.com/KatthTV',
            youtube: 'https://www.youtube.com/channel/UCxTku5OSXcO7HYzAKi8KxRg',
        },
        {
            name: 'bladecito',
            img: '../../../assets/exclusives/bladecito.jpg',
            instagram: 'https://www.instagram.com/bladecito_/',
            twitch: 'https://www.twitch.tv/bladecito',
            twitter: 'https://twitter.com/Bladecito_',
            youtube: 'https://www.youtube.com/user/bladecitolol',
        },
        {
            name: 'el churches',
            img: '../../../assets/exclusives/churches.jpg',
            instagram: 'https://www.instagram.com/elchurchesoficial/',
            twitch: 'https://www.twitch.tv/elchurches',
            twitter: 'https://twitter.com/ElChurchesYT',
            youtube: 'https://www.youtube.com/user/ElChurches',
        },
        {
            name: 'juanludbz',
            img: '../../../assets/exclusives/JuanluDBZ.jpg',
            instagram: 'https://www.instagram.com/juanludbz/',
            twitch: 'https://www.twitch.tv/juanludbz',
            twitter: 'https://twitter.com/JuanluDBZ',
            youtube: 'https://www.youtube.com/user/JuanluDBZfifa',
        },
        {
            name: 'fesbak',
            img: '../../../assets/exclusives/Fesbak.jpg',
            instagram: 'https://www.instagram.com/fesbak_official/',
            twitch: 'https://www.twitch.tv/fesbak',
            twitter: 'https://twitter.com/Fesbak_official',
            youtube: 'https://www.youtube.com/channel/UCGMJt-JajJDjYC29ApCdIxA',
        },
        {
            name: 'elxokas',
            img: '../../../assets/exclusives/elxokas.jpg',
            instagram: 'https://www.instagram.com/elxokas/',
            twitch: 'https://www.twitch.tv/elxokas',
            twitter: 'https://twitter.com/Elxokas',
            youtube: 'https://www.youtube.com/user/elxokas',
        },
        {
            name: 'diamond',
            img: '../../../assets/exclusives/diamond.jpg',
            instagram: '',
            twitch: 'https://www.twitch.tv/iamdiamond',
            twitter: 'https://twitter.com/IamDiamondLoL',
            youtube: 'https://www.youtube.com/channel/UCho7Rx-v1bt2oSwcPR3F',
        },
        {
            name: 'aroyitt',
            img: '../../../assets/exclusives/aroyitt.png',
            instagram: 'https://www.instagram.com/aroiagarcia/',
            twitch: 'https://www.twitch.tv/aroyitt/',
            twitter: 'https://twitter.com/aroiagarcia',
            youtube: 'https://www.youtube.com/aroyitt',
        },
        {
            name: 'ray snakeyes',
            img: '../../../assets/exclusives/raySnakeyes.jpg',
            instagram: 'https://www.instagram.com/raysnakeyes/',
            twitch: '',
            twitter: 'https://twitter.com/raysnakeyes',
            youtube: 'https://www.youtube.com/user/assassinsmania',
        },
        {
            name: 'alex segura',
            img: '../../../assets/exclusives/AlexSegura.jpg',
            instagram: 'https://www.instagram.com/AlexSeguraLR',
            twitch: 'https://www.twitch.tv/AlexSeguraLROficial',
            twitter: '',
            youtube: 'https://www.youtube.com/channel/UCfAQIflIplQ3FlwrQX',
        },
        {
            name: 'jin kisaragi',
            img: '../../../assets/exclusives/JinKisaragi.png',
            instagram: 'https://www.instagram.com/AlexSeguraLR',
            twitch: 'https://www.twitch.tv/jinkisaragi',
            twitter: 'https://twitter.com/Sephi_Tetsu',
            youtube: 'https://www.youtube.com/user/JinKisaragiHD',
        },
    ];

    constructor() {}
}
