import { Component } from '@angular/core';
import { Influencer } from 'src/types/influencer';

@Component({
    selector: 'app-collaborators',
    templateUrl: './collaborators.component.html',
})
export class CollaboratorsComponent {
    detailsCard: Influencer[] = [
        {
            name: 'evangelion',
            img: '../../../assets/colaborators/evangelion.png',
            instagram: '',
            twitch: 'https://www.twitch.tv/evangelion0',
            twitter: 'https://twitter.com/EvangelionEldar',
            youtube: 'https://www.youtube.com/channel/UCeetGyp_Poia9axuVFzUt0w',
        },
        {
            name: 'manucraft',
            img: '../../../assets/colaborators/manucraft.jpg',
            instagram: 'https://www.instagram.com/manucraft/',
            twitch: '',
            twitter: 'https://twitter.com/manucrafting',
            youtube: 'https://www.youtube.com/channel/UCVoKxxQdeckWgU6DQGZCoIw',
        },
        {
            name: 'mada',
            img: '../../../assets/colaborators/Mada.jpg',
            instagram: 'https://www.instagram.com/madapls/',
            twitch: 'https://www.twitch.tv/mada/',
            twitter: 'https://twitter.com/madapls',
            youtube: '',
        },
        {
            name: 'djmario',
            img: '../../../assets/colaborators/djmario.jpg',
            instagram: 'https://www.instagram.com/DjMaRiiO/',
            twitch: 'https://www.twitch.tv/DjMaRiiO',
            twitter: 'https://twitter.com/DjMaRiiO',
            youtube: 'https://www.youtube.com/user/DjMaRiiO',
        },
        {
            name: 'bydiegox10',
            img: '../../../assets/colaborators/bydiegox10.jpg',
            instagram: 'https://www.instagram.com/bydiegox10/',
            twitch: 'https://www.twitch.tv/bydiegox10',
            twitter: 'https://twitter.com/ByDiegoX10',
            youtube: 'https://www.youtube.com/user/ByDiegoX10',
        },
        {
            name: '8cho',
            img: '../../../assets/colaborators/8cho.jpg',
            instagram: 'https://www.instagram.com/8cho.oficial/',
            twitch: 'https://www.twitch.tv/8cho/',
            twitter: '',
            youtube: 'https://www.youtube.com/user/TodoTopsOficial',
            youtubeSecondary:
                'https://www.youtube.com/channel/UClOTXvBhNkVce1J8gsXncAw',
        },
        {
            name: 'xbuyer',
            img: '../../../assets/colaborators/xbuyer.jpg',
            instagram: 'https://www.instagram.com/xbuyer/',
            twitch: 'https://www.twitch.tv/xbuyer',
            twitter: 'https://twitter.com/1996Javi',
            youtube: 'https://www.youtube.com/user/xBuyer',
        },
        {
            name: 'luh',
            img: '../../../assets/colaborators/luh.jpg',
            instagram: 'https://www.instagram.com/hdluh/',
            twitch: 'https://www.twitch.tv/luh',
            twitter: 'https://twitter.com/HDluh',
            youtube: 'https://www.youtube.com/user/HDluh',
        },
        {
            name: 'zellendust',
            img: '../../../assets/colaborators/zellendust.jpg',
            instagram: 'https://www.instagram.com/zellendust/',
            twitch: 'https://www.twitch.tv/zellendust',
            twitter: 'https://twitter.com/ZellenDust',
            youtube: 'https://www.youtube.com/user/ZellenDust',
        },
        {
            name: 'pokerg88tv',
            img: '../../../assets/colaborators/poker.jpg',
            instagram: 'https://www.instagram.com/poker_official/',
            twitch: '',
            twitter: 'https://twitter.com/PokeR988HD',
            youtube: 'https://www.youtube.com/user/PokeR988TV',
        },
        {
            name: 'cacho01',
            img: '../../../assets/colaborators/cacho01.jpg',
            instagram: 'https://www.instagram.com/cachoo01/',
            twitch: 'https://www.twitch.tv/cacho01',
            twitter: 'https://twitter.com/cachoo01',
            youtube: 'https://www.youtube.com/user/cach',
        },
        {
            name: 'ninchiboy',
            img: '../../../assets/colaborators/Ninchiboy.jpg',
            instagram: 'https://www.instagram.com/ninchiboy_/',
            twitch: 'https://www.twitch.tv/Ninchiboy_',
            twitter: 'https://twitter.com/ninchiboy',
            youtube: 'https://www.youtube.com/user/NinchiBoy3',
        },
        {
            name: 'yosoyplex',
            img: '../../../assets/colaborators/YoSoyPlex.jpg',
            instagram: 'https://www.instagram.com/yosoyplex/',
            twitch: '',
            twitter: 'https://twitter.com/YoSoyPlex',
            youtube: 'https://www.youtube.com/channel/UCl8bYBm0XAP23mReE11IBOA',
        },
        {
            name: 'atack3000',
            img: '../../../assets/colaborators/atack3000.jpg',
            instagram: 'https://www.instagram.com/atack3000yt/',
            twitch: '',
            twitter: 'https://twitter.com/atack3000',
            youtube: 'https://www.youtube.com/channel/UCQNDd94ASHH2d_JHn-FHY0A',
        },
        {
            name: 'spursito',
            img: '../../../assets/colaborators/Spursito.jpg',
            instagram: 'https://www.instagram.com/martimiras/',
            twitch: 'https://www.twitch.tv/spursito',
            twitter: 'https://twitter.com/Spursito',
            youtube: 'https://www.youtube.com/channel/UC8h85qEsJ25Os5THPu6QpHg',
        },
        {
            name: 'pumuscor',
            img: '../../../assets/colaborators/Pumuscor.jpg',
            instagram: 'https://www.instagram.com/pumuscorx/',
            twitch: '',
            twitter: 'https://twitter.com/Pumuscor',
            youtube: 'https://www.youtube.com/user/pumuscor',
        },
        {
            name: 'papigavi',
            img: '../../../assets/colaborators/papigavi.jpg',
            instagram: 'https://www.instagram.com/agavilanyt/',
            twitch: 'https://www.twitch.tv/papigavitv',
            twitter: 'https://twitter.com/papigavi',
            youtube: 'https://www.youtube.com/user/elcanaldeguilleygavi',
        },
        {
            name: 'vituber',
            img: '../../../assets/colaborators/vituber.jpg',
            instagram: 'https://www.instagram.com/agavilanyt/',
            twitch: 'https://www.twitch.tv/vitu',
            twitter: 'https://twitter.com/vitu_yt',
            youtube: 'https://www.youtube.com/user/ViTuberYT',
        },
        {
            name: 'miikelmst',
            img: '../../../assets/colaborators/MIKeL.jpg',
            instagram: 'https://www.instagram.com/agavilanyt/',
            twitch: 'https://www.twitch.tv/miikelmst',
            twitter: 'https://twitter.com/MiiKeLMsT',
            youtube: 'https://www.youtube.com/user/miikelmst',
        },
        {
            name: 'ariian',
            img: '../../../assets/colaborators/Ariian.jpg',
            instagram: 'https://www.instagram.com/xariian/',
            twitch: 'https://www.twitch.tv/ariian',
            twitter: 'https://twitter.com/xARiiAN',
            youtube: 'https://www.youtube.com/user/xARIANRENK1HD',
        },
        {
            name: 'powerbazinga',
            img: '../../../assets/colaborators/powerbazinga.png',
            instagram: '',
            twitch: 'https://www.twitch.tv/powerbazinga_tv',
            twitter: 'https://twitter.com/Powerbazinga',
            youtube: 'https://www.youtube.com/user/powerbazinga',
        },
        {
            name: 'warchiwar',
            img: '../../../assets/colaborators/Warchiwar.jpg',
            instagram: 'https://www.instagram.com/warchiwaroficial/',
            twitch: 'https://www.twitch.tv/warchiwar',
            twitter: 'https://twitter.com/warchiwar',
            youtube: 'https://www.youtube.com/user/warchiwar',
        },
        {
            name: 'cabravoladora',
            img: '../../../assets/colaborators/Cabravoladora.jpg',
            instagram: '',
            twitch: 'https://www.twitch.tv/cabravoladora',
            twitter: 'https://twitter.com/cabravoladora',
            youtube: 'https://www.youtube.com/channel/UCWWb1STGKJzOG0Di93JsB_A',
        },
        {
            name: 'dsimphony',
            img: '../../../assets/colaborators/DSimphony.png',
            instagram: 'https://www.instagram.com/DSimphony/',
            twitch: 'https://www.twitch.tv/dsimphony',
            twitter: 'https://twitter.com/dsimphony',
            youtube: 'https://www.youtube.com/user/DSimphonyHD',
        },
        {
            name: 'vicio',
            img: '../../../assets/colaborators/vicio.jpg',
            instagram: 'https://www.instagram.com/vicioomtoficial/',
            twitch: 'https://www.twitch.tv/vicioonemoretime',
            twitter: 'https://twitter.com/VicioOMT',
            youtube: 'https://www.youtube.com/user/1upDav',
        },
        {
            name: 'coolifegame',
            img: '../../../assets/colaborators/coolifegame.jpg',
            instagram: '',
            twitch: 'https://www.twitch.tv/coolifegame',
            twitter: 'https://twitter.com/coolifegame',
            youtube: 'https://www.youtube.com/user/CooLifeGame',
        },
        {
            name: 'dontomasgamer',
            img: '../../../assets/colaborators/DonTomasGamer.jpg',
            instagram: 'https://www.instagram.com/dontomasgamer/',
            twitch: 'https://www.twitch.tv/dontomasgamer',
            twitter: 'https://twitter.com/DonTomasGamer',
            youtube: 'https://www.youtube.com/user/DonTomasGamer',
        },
        {
            name: 'theexal04',
            img: '../../../assets/colaborators/TheExal04.jpg',
            instagram: 'https://www.instagram.com/theexal04/',
            twitch: 'https://www.twitch.tv/theexal04',
            twitter: 'https://twitter.com/TheExaL04',
            youtube: 'https://www.youtube.com/channel/UCSblay-r16Uf-N-MIJ6X3Gw',
        },
        {
            name: 'mery soldier',
            img: '../../../assets/colaborators/merysoldier.jpg',
            instagram: 'https://www.instagram.com/mery_soldier/',
            twitch: 'https://www.twitch.tv/mery_soldier',
            twitter: 'https://twitter.com/mery_soldier',
            youtube: 'https://www.youtube.com/channel/UCI4i5O3BPZZWbbX4J345crA',
        },
        {
            name: 'cristinini',
            img: '../../../assets/colaborators/cristinini.jpg',
            instagram: 'https://twitter.com/IamCristinini',
            twitch: 'https://www.twitch.tv/iamcristinini',
            twitter: 'https://twitter.com/IamCristinini',
            youtube: 'https://www.youtube.com/channel/UCCuNpAi5cNF4x-hcW2qawhw',
        },
        {
            name: 'elojoninja',
            img: '../../../assets/colaborators/elojoninja.png',
            instagram: 'https://www.instagram.com/elojoninja/?hl=es',
            twitch: 'https://www.twitch.tv/elojoninja',
            twitter: 'https://twitter.com/ElOjoNinja',
            youtube: 'https://www.youtube.com/channel/UCtU5YaiBnanZC47u1MVOD6Q',
        },
        {
            name: 'heikki360es',
            img: '../../../assets/colaborators/heikki.jpg',
            instagram: '',
            twitch: 'https://www.twitch.tv/heikki360es',
            twitter: 'https://twitter.com/heikki360',
            youtube: 'https://www.youtube.com/user/Heikki360ES',
        },
    ];
}
